"use client";
import {useEffect,useState} from "react";
import {api,Button,clearSession,EmptyState,money,Pill,PortalShell,saveSession,Stat} from "@ppm/ui";
export default function RestaurantPortal(){
 const [logged,setLogged]=useState(false),[identifier,setIdentifier]=useState(""),[password,setPassword]=useState(""),[orders,setOrders]=useState<any[]>([]),[restaurants,setRestaurants]=useState<any[]>([]),[message,setMessage]=useState("");
 useEffect(()=>{setLogged(!!sessionStorage.getItem("ppm_access_token"));},[]);
 useEffect(()=>{if(logged)load()},[logged]);
 async function login(e:React.FormEvent){e.preventDefault();try{const d:any=await api("/auth/login",{method:"POST",body:JSON.stringify({identifier,password})});saveSession(d);setLogged(true);setPassword("")}catch(e:any){setMessage(e.message)}}
 async function load(){try{const [o,r]:any=await Promise.all([api("/partner/orders"),api("/partner/restaurants")]);setOrders(o);setRestaurants(r)}catch(e:any){setMessage(e.message)}}
 async function transition(id:string,to:string){try{await api("/orders/"+id+"/transition",{method:"POST",body:JSON.stringify({to})});await load()}catch(e:any){setMessage(e.message)}}
 if(!logged)return <main className="mx-auto max-w-md p-5 pt-20"><div className="card"><span className="eyebrow">RESTAURANT PARTNER</span><h1 className="my-3 text-3xl font-black">Run your kitchen</h1><p className="muted">Sign in with your restaurant partner account.</p><form className="stack mt-5" onSubmit={login}><input className="input" placeholder="Partner email or phone" value={identifier} onChange={e=>setIdentifier(e.target.value)} required/><input className="input" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit">Sign in</Button></form></div>{message&&<div className="toast">{message}</div>}</main>;
 const active=orders.filter(o=>!["DELIVERED","CANCELLED"].includes(o.status));
 return <PortalShell title="Restaurant operations" nav={["Dashboard","Orders","Menu","Offers","Reviews","Analytics","Payouts","Settings","Support"]} active="Dashboard" actions={<div className="flex gap-2"><Button variant="secondary" onClick={load}>Refresh</Button><Button variant="ghost" onClick={()=>{clearSession();setLogged(false)}}>Sign out</Button></div>}>
  <div className="grid cols-4 mb-5"><Stat label="Active orders" value={active.length}/><Stat label="Restaurants" value={restaurants.length}/><Stat label="Awaiting acceptance" value={orders.filter(o=>o.status==="PLACED").length}/><Stat label="Ready for pickup" value={orders.filter(o=>o.status==="READY_FOR_PICKUP").length}/></div>
  <div className="grid cols-2"><section className="card"><div className="split"><div><span className="eyebrow">LIVE QUEUE</span><h2 className="text-xl font-bold">Incoming orders</h2></div><Pill tone="success">● Live</Pill></div>{active.length?<div className="list mt-4">{active.map(o=><div className="row" key={o.id}><div><b>{o.orderNumber}</b><div className="muted text-sm">{o.items.map((i:any)=>i.quantity+"× "+i.nameSnapshot).join(", ")}</div><div className="mt-1 font-bold">{money(o.totalPaise)}</div></div><div className="flex flex-wrap justify-end gap-2"><Pill tone="warning">{o.status.replaceAll("_"," ")}</Pill>{o.status==="PLACED"&&<Button onClick={()=>transition(o.id,"RESTAURANT_CONFIRMED")}>Accept</Button>}{o.status==="RESTAURANT_CONFIRMED"&&<Button onClick={()=>transition(o.id,"PREPARING")}>Start prep</Button>}{["PREPARING","DELIVERY_PARTNER_ASSIGNED"].includes(o.status)&&<Button onClick={()=>transition(o.id,"READY_FOR_PICKUP")}>Ready</Button>}</div></div>)}</div>:<EmptyState title="No active orders" body="New orders will appear here after checkout."/>}</section>
  <section className="card"><span className="eyebrow">STORE STATUS</span><h2 className="text-xl font-bold">Your restaurants</h2><div className="list mt-4">{restaurants.map(r=><div className="row" key={r.id}><div><b>{r.name}</b><div className="muted text-sm">{r.address}</div></div><Pill tone={r.isOpen&&!r.isPaused?"success":"danger"}>{r.isPaused?"Paused":r.isOpen?"Open":"Closed"}</Pill></div>)}</div></section></div>{message&&<div className="toast">{message}</div>}
 </PortalShell>;
}
