"use client";
import {useEffect,useState} from "react";
import {api,Button,clearSession,EmptyState,money,Pill,PortalShell,saveSession,Stat} from "@ppm/ui";

export default function RestaurantPortal(){
 const [logged,setLogged]=useState(false),[identifier,setIdentifier]=useState(""),[password,setPassword]=useState("");
 const [orders,setOrders]=useState<any[]>([]),[restaurants,setRestaurants]=useState<any[]>([]),[settlements,setSettlements]=useState<any>({totalPayoutPaise:0,entries:[]}),[reviews,setReviews]=useState<any[]>([]),[message,setMessage]=useState("");
 useEffect(()=>{setLogged(!!sessionStorage.getItem("ppm_access_token"));},[]);
 useEffect(()=>{if(logged)load()},[logged]);
 async function login(e:React.FormEvent){e.preventDefault();try{const d:any=await api("/auth/login",{method:"POST",body:JSON.stringify({identifier,password})});saveSession(d);setLogged(true);setPassword("")}catch(e:any){setMessage(e.message)}}
 async function load(){try{const [o,r,s,v]:any=await Promise.all([api("/partner/orders"),api("/partner/restaurants"),api("/partner/settlements"),api("/partner/reviews")]);setOrders(o);setRestaurants(r);setSettlements(s);setReviews(v)}catch(e:any){setMessage(e.message)}}
 async function transition(id:string,to:string){try{await api("/orders/"+id+"/transition",{method:"POST",body:JSON.stringify({to})});await load()}catch(e:any){setMessage(e.message)}}
 async function reply(review:any){const text=window.prompt("Reply to this review",review.restaurantReply??"");if(!text)return;try{await api("/partner/reviews/"+review.id+"/reply",{method:"POST",body:JSON.stringify({reply:text})});await load()}catch(e:any){setMessage(e.message)}}

 if(!logged)return <main className="mx-auto max-w-md p-5 pt-20"><div className="card"><span className="eyebrow">RESTAURANT PARTNER</span><h1 className="my-3 text-3xl font-black">Run your kitchen</h1><p className="muted">Sign in with your restaurant partner account.</p><form className="stack mt-5" onSubmit={login}><input className="input" placeholder="Partner email or phone" value={identifier} onChange={e=>setIdentifier(e.target.value)} required/><input className="input" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit">Sign in</Button></form></div>{message&&<div className="toast">{message}</div>}</main>;
 const active=orders.filter(o=>!["DELIVERED","CANCELLED"].includes(o.status));
 const approved=restaurants.filter(r=>r.status==="APPROVED");

 return <PortalShell title="Restaurant operations" nav={["Dashboard","Orders","Menu","Offers","Reviews","Analytics","Payouts","Settings","Support"]} active="Dashboard" actions={<div className="flex gap-2"><Button variant="secondary" onClick={load}>Refresh</Button><Button variant="ghost" onClick={()=>{clearSession();setLogged(false)}}>Sign out</Button></div>}>
  <div className="grid cols-4 mb-5"><Stat label="Active orders" value={active.length}/><Stat label="Approved restaurants" value={approved.length}/><Stat label="Awaiting acceptance" value={orders.filter(o=>o.status==="PLACED").length}/><Stat label="Recorded payouts" value={money(settlements.totalPayoutPaise??0)}/></div>
  <div className="grid cols-2"><section className="card"><div className="split"><div><span className="eyebrow">LIVE QUEUE</span><h2 className="text-xl font-bold">Incoming orders</h2></div><Pill tone="success">● Live</Pill></div>{active.length?<div className="list mt-4">{active.map(o=><div className="row" key={o.id}><div><b>{o.orderNumber}</b><div className="muted text-sm">{o.items.map((i:any)=>i.quantity+"× "+i.nameSnapshot).join(", ")}</div><div className="mt-1 font-bold">{money(o.totalPaise)}</div></div><div className="flex flex-wrap justify-end gap-2"><Pill tone="warning">{o.status.replaceAll("_"," ")}</Pill>{o.status==="PLACED"&&<Button onClick={()=>transition(o.id,"RESTAURANT_CONFIRMED")}>Accept</Button>}{o.status==="RESTAURANT_CONFIRMED"&&<Button onClick={()=>transition(o.id,"PREPARING")}>Start prep</Button>}{["PREPARING","DELIVERY_PARTNER_ASSIGNED"].includes(o.status)&&<Button onClick={()=>transition(o.id,"READY_FOR_PICKUP")}>Ready</Button>}</div></div>)}</div>:<EmptyState title="No active orders" body="New orders will appear here after checkout."/>}</section>
  <section className="card"><span className="eyebrow">STORE STATUS</span><h2 className="text-xl font-bold">Your restaurants</h2><div className="list mt-4">{restaurants.map(r=><div className="row" key={r.id}><div><b>{r.name}</b><div className="muted text-sm">{r.address}</div></div><Pill tone={r.status!=="APPROVED"?"warning":r.isOpen&&!r.isPaused?"success":"danger"}>{r.status!=="APPROVED"?r.status.replaceAll("_"," "):r.isPaused?"Paused":r.isOpen?"Open":"Closed"}</Pill></div>)}</div></section></div>
  <div className="grid cols-2 mt-5"><section className="card"><span className="eyebrow">PAYOUT LEDGER</span><h2 className="text-xl font-bold">Recent settlements</h2>{settlements.entries?.length?<div className="list mt-4">{settlements.entries.slice(0,10).map((s:any)=><div className="row" key={s.id}><div><b>{s.order?.orderNumber??"Order"}</b><div className="muted text-sm">{s.status.replaceAll("_"," ")}</div></div><b>{money(s.payoutPaise)}</b></div>)}</div>:<EmptyState title="No settlements yet" body="Delivered orders will create settlement entries."/>}</section>
  <section className="card"><span className="eyebrow">CUSTOMER FEEDBACK</span><h2 className="text-xl font-bold">Latest reviews</h2>{reviews.length?<div className="list mt-4">{reviews.slice(0,8).map((r:any)=><div key={r.id} className="rounded-xl border border-[#e9e4dc] p-3"><div className="split"><b>★ {r.restaurantRating}/5</b><span className="muted text-xs">{r.user?.profile?.name??"Customer"}</span></div><p className="mt-2 text-sm">{r.text||"No written comment"}</p>{r.restaurantReply&&<p className="muted mt-2 text-sm"><b>Your reply:</b> {r.restaurantReply}</p>}<Button variant="ghost" onClick={()=>reply(r)} style={{marginTop:8}}>Reply</Button></div>)}</div>:<EmptyState title="No reviews yet" body="Verified delivered-order reviews will appear here."/>}</section></div>{message&&<div className="toast">{message}</div>}
 </PortalShell>;
}
