"use client";
import {useEffect,useMemo,useState} from "react";
import {api,Button,clearSession,EmptyState,money,Pill,PortalShell,saveSession,Stat} from "@ppm/ui";

type Tab="Dashboard"|"Orders"|"Menu"|"Offers"|"Reviews"|"Analytics"|"Payouts"|"Settings"|"Staff"|"Support";

export default function RestaurantPortal(){
 const [logged,setLogged]=useState(false),[identifier,setIdentifier]=useState(""),[password,setPassword]=useState("");
 const [tab,setTab]=useState<Tab>("Dashboard"),[orders,setOrders]=useState<any[]>([]),[restaurants,setRestaurants]=useState<any[]>([]);
 const [settlements,setSettlements]=useState<any>({totalPayoutPaise:0,entries:[]}),[reviews,setReviews]=useState<any[]>([]);
 const [selectedId,setSelectedId]=useState(""),[menu,setMenu]=useState<any>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [categoryName,setCategoryName]=useState(""),[item,setItem]=useState({categoryId:"",name:"",description:"",price:"",veg:true}),[staff,setStaff]=useState({email:"",role:"RESTAURANT_STAFF"});
 const [promotion,setPromotion]=useState({title:"",description:"",kind:"DISCOUNT",startsAt:"",endsAt:""});
 useEffect(()=>{setLogged(!!sessionStorage.getItem("ppm_access_token"));},[]);
 useEffect(()=>{if(logged)load()},[logged]);
 useEffect(()=>{if(selectedId)loadMenu(selectedId)},[selectedId]);

 async function login(e:React.FormEvent){e.preventDefault();try{const d:any=await api("/auth/login",{method:"POST",body:JSON.stringify({identifier,password})});saveSession(d);setLogged(true);setPassword("")}catch(e:any){setMessage(e.message)}}
 async function load(){
   try{
    const [o,r,s,v]:any=await Promise.all([api("/partner/orders"),api("/partner/restaurants"),api("/partner/settlements"),api("/partner/reviews")]);
    setOrders(o);setRestaurants(r);setSettlements(s);setReviews(v);
    if(!selectedId&&r.length)setSelectedId(r[0].id);
   }catch(e:any){setMessage(e.message)}
 }
 async function loadMenu(id=selectedId){if(!id)return;try{setMenu(await api("/partner/restaurants/"+id+"/menu"))}catch(e:any){setMessage(e.message)}}
 async function transition(id:string,to:string){try{await api("/orders/"+id+"/transition",{method:"POST",body:JSON.stringify({to})});await load()}catch(e:any){setMessage(e.message)}}
 async function reply(review:any){const text=window.prompt("Reply to this review",review.restaurantReply??"");if(!text)return;try{await api("/partner/reviews/"+review.id+"/reply",{method:"POST",body:JSON.stringify({reply:text})});await load()}catch(e:any){setMessage(e.message)}}
 async function createCategory(e:React.FormEvent){e.preventDefault();if(!selectedId)return;setBusy(true);try{await api("/partner/restaurants/"+selectedId+"/categories",{method:"POST",body:JSON.stringify({name:categoryName})});setCategoryName("");await loadMenu()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function createItem(e:React.FormEvent){e.preventDefault();if(!selectedId||!item.categoryId)return;setBusy(true);try{await api("/partner/restaurants/"+selectedId+"/items",{method:"POST",body:JSON.stringify({categoryId:item.categoryId,name:item.name,description:item.description||undefined,pricePaise:Math.round(Number(item.price)*100),veg:item.veg})});setItem({categoryId:item.categoryId,name:"",description:"",price:"",veg:true});await loadMenu()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function toggleItem(i:any){try{await api("/partner/items/"+i.id,{method:"PATCH",body:JSON.stringify({available:!i.available})});await loadMenu()}catch(e:any){setMessage(e.message)}}
 async function editPrice(i:any){const p=window.prompt("New price in rupees",String((i.pricePaise/100).toFixed(0)));if(!p)return;try{await api("/partner/items/"+i.id,{method:"PATCH",body:JSON.stringify({pricePaise:Math.round(Number(p)*100)})});await loadMenu()}catch(e:any){setMessage(e.message)}}
 async function archiveItem(i:any){if(!confirm("Archive "+i.name+"?"))return;try{await api("/partner/items/"+i.id,{method:"DELETE"});await loadMenu()}catch(e:any){setMessage(e.message)}}
 async function addVariant(i:any){const name=prompt("Variant name, e.g. Large");if(!name)return;const delta=Number(prompt("Extra price in rupees","0")??0);try{await api("/partner/items/"+i.id+"/variants",{method:"POST",body:JSON.stringify({name,priceDeltaPaise:Math.round(delta*100)})});await loadMenu()}catch(e:any){setMessage(e.message)}}
 async function addAddonGroup(i:any){const name=prompt("Add-on group name, e.g. Extras");if(!name)return;try{const g:any=await api("/partner/restaurants/"+selectedId+"/addon-groups",{method:"POST",body:JSON.stringify({name,maxSelect:3})});const addonName=prompt("First add-on name, e.g. Extra cheese");if(addonName){const price=Number(prompt("Add-on price in rupees","0")??0);await api("/partner/addon-groups/"+g.id+"/addons",{method:"POST",body:JSON.stringify({name:addonName,pricePaise:Math.round(price*100)})});}await api("/partner/items/"+i.id+"/addon-groups/"+g.id,{method:"POST"});await loadMenu()}catch(e:any){setMessage(e.message)}}
 async function settingsPatch(body:any){try{const r:any=await api("/partner/restaurants/"+selectedId+"/settings",{method:"PATCH",body:JSON.stringify(body)});setRestaurants(xs=>xs.map(x=>x.id===r.id?r:x));await loadMenu()}catch(e:any){setMessage(e.message)}}
 async function saveHours(){
   const open=prompt("Opening time (HH:MM)","09:00"),close=prompt("Closing time (HH:MM)","22:00");if(!open||!close)return;
   try{await api("/partner/restaurants/"+selectedId+"/hours",{method:"PUT",body:JSON.stringify({hours:[0,1,2,3,4,5,6].map(weekday=>({weekday,shift:1,opensAt:open,closesAt:close,closed:false}))})});await loadMenu();setMessage("Opening hours updated")}catch(e:any){setMessage(e.message)}
 }
 async function createPromotion(e:React.FormEvent){e.preventDefault();try{await api("/partner/restaurants/"+selectedId+"/promotions",{method:"POST",body:JSON.stringify({...promotion,startsAt:new Date(promotion.startsAt).toISOString(),endsAt:new Date(promotion.endsAt).toISOString()})});setPromotion({title:"",description:"",kind:"DISCOUNT",startsAt:"",endsAt:""});await loadMenu()}catch(e:any){setMessage(e.message)}}
 async function addStaff(e:React.FormEvent){e.preventDefault();try{await api("/partner/restaurants/"+selectedId+"/staff",{method:"POST",body:JSON.stringify(staff)});setStaff({email:"",role:"RESTAURANT_STAFF"});setMessage("Staff access added")}catch(e:any){setMessage(e.message)}}

 if(!logged)return <main className="mx-auto max-w-md p-5 pt-20"><div className="card"><span className="eyebrow">RESTAURANT PARTNER</span><h1 className="my-3 text-3xl font-black">Run your kitchen</h1><p className="muted">Sign in with your restaurant partner account.</p><form className="stack mt-5" onSubmit={login}><input className="input" placeholder="Partner email or phone" value={identifier} onChange={e=>setIdentifier(e.target.value)} required/><input className="input" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit">Sign in</Button></form></div>{message&&<div className="toast">{message}</div>}</main>;

 const active=orders.filter(o=>!["DELIVERED","CANCELLED"].includes(o.status));
 const approved=restaurants.filter(r=>r.status==="APPROVED");
 const selected=restaurants.find(r=>r.id===selectedId);
 const nav:Tab[]=["Dashboard","Orders","Menu","Offers","Reviews","Analytics","Payouts","Settings","Staff","Support"];
 const action=<div className="flex flex-wrap gap-2"><select className="input !w-auto" value={selectedId} onChange={e=>setSelectedId(e.target.value)}>{restaurants.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><Button variant="secondary" onClick={()=>{load();loadMenu()}}>Refresh</Button><Button variant="ghost" onClick={()=>{clearSession();setLogged(false)}}>Sign out</Button></div>;

 return <PortalShell title="Restaurant operations" nav={nav} active={tab} actions={action}>
  <div className="mb-5 flex gap-2 overflow-auto pb-1">{nav.map(n=><Button key={n} variant={tab===n?"primary":"ghost"} onClick={()=>setTab(n)}>{n}</Button>)}</div>

  {tab==="Dashboard"&&<>
   <div className="grid cols-4 mb-5"><Stat label="Active orders" value={active.length}/><Stat label="Approved restaurants" value={approved.length}/><Stat label="Awaiting acceptance" value={orders.filter(o=>o.status==="PLACED").length}/><Stat label="Recorded payouts" value={money(settlements.totalPayoutPaise??0)}/></div>
   <div className="grid cols-2"><OrderQueue orders={active} transition={transition}/><StoreStatus restaurants={restaurants}/></div>
  </>}

  {tab==="Orders"&&<OrderQueue orders={active} transition={transition}/>}
  {tab==="Menu"&&<section className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]">
    <div className="card"><div className="split"><div><span className="eyebrow">MENU BUILDER</span><h2 className="text-xl font-bold">{selected?.name??"Restaurant"} menu</h2></div><Pill tone="success">{menu?.categories?.reduce((s:number,c:any)=>s+c.items.length,0)??0} items</Pill></div>
      {menu?.categories?.length?<div className="mt-5 space-y-5">{menu.categories.map((cat:any)=><div key={cat.id}><div className="split border-b border-[#e9e4dc] pb-2"><h3 className="font-bold">{cat.name}</h3><Pill>{cat.items.length} items</Pill></div><div className="list">{cat.items.map((i:any)=><div className="row" key={i.id}><div><div className="font-bold">{i.veg?"🟢":"🔴"} {i.name}</div><div>{money(i.pricePaise)} {i.stock!==null&&<span className="muted">· stock {i.stock}</span>}</div><div className="mt-1 flex flex-wrap gap-1">{i.variants.map((v:any)=><Pill key={v.id}>{v.name} {v.priceDeltaPaise?money(v.priceDeltaPaise):""}</Pill>)}{i.addonLinks.map((x:any)=><Pill key={x.group.id}>{x.group.name}</Pill>)}</div></div><div className="flex flex-wrap justify-end gap-1"><Button variant={i.available?"secondary":"danger"} onClick={()=>toggleItem(i)}>{i.available?"Available":"Sold out"}</Button><Button variant="ghost" onClick={()=>editPrice(i)}>Price</Button><Button variant="ghost" onClick={()=>addVariant(i)}>Variant</Button><Button variant="ghost" onClick={()=>addAddonGroup(i)}>Add-ons</Button><Button variant="danger" onClick={()=>archiveItem(i)}>Archive</Button></div></div>)}</div></div>)}</div>:<EmptyState title="No menu yet" body="Create your first category and item."/>}
    </div>
    <div className="stack"><form className="card stack" onSubmit={createCategory}><h3 className="font-bold">New category</h3><input className="input" required placeholder="e.g. Biryani" value={categoryName} onChange={e=>setCategoryName(e.target.value)}/><Button disabled={busy}>Add category</Button></form>
    <form className="card stack" onSubmit={createItem}><h3 className="font-bold">New menu item</h3><select className="input" required value={item.categoryId} onChange={e=>setItem({...item,categoryId:e.target.value})}><option value="">Choose category</option>{menu?.categories?.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="input" required placeholder="Dish name" value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/><textarea className="input min-h-20 py-3" placeholder="Description" value={item.description} onChange={e=>setItem({...item,description:e.target.value})}/><input className="input" required type="number" min="1" step="0.01" placeholder="Price ₹" value={item.price} onChange={e=>setItem({...item,price:e.target.value})}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={item.veg} onChange={e=>setItem({...item,veg:e.target.checked})}/> Vegetarian</label><Button disabled={busy}>Create item</Button></form></div>
  </section>}

  {tab==="Offers"&&<section className="grid cols-2"><form className="card stack" onSubmit={createPromotion}><span className="eyebrow">PROMOTIONS</span><h2 className="text-xl font-bold">Create restaurant offer</h2><input className="input" required placeholder="Offer title" value={promotion.title} onChange={e=>setPromotion({...promotion,title:e.target.value})}/><textarea className="input min-h-20 py-3" placeholder="Description" value={promotion.description} onChange={e=>setPromotion({...promotion,description:e.target.value})}/><select className="input" value={promotion.kind} onChange={e=>setPromotion({...promotion,kind:e.target.value})}><option>DISCOUNT</option><option>FREE_DELIVERY</option><option>FEATURED</option></select><label className="text-sm">Start<input className="input mt-1" required type="datetime-local" value={promotion.startsAt} onChange={e=>setPromotion({...promotion,startsAt:e.target.value})}/></label><label className="text-sm">End<input className="input mt-1" required type="datetime-local" value={promotion.endsAt} onChange={e=>setPromotion({...promotion,endsAt:e.target.value})}/></label><Button>Create offer</Button></form><section className="card"><h2 className="text-xl font-bold">Current promotions</h2>{menu?.promotions?.length?<div className="list mt-4">{menu.promotions.map((p:any)=><div key={p.id} className="row"><div><b>{p.title}</b><div className="muted text-sm">{p.kind}</div></div><Pill tone={p.active?"success":"neutral"}>{p.active?"Active":"Inactive"}</Pill></div>)}</div>:<EmptyState title="No promotions" body="Create a dated promotional campaign."/>}</section></section>}

  {tab==="Reviews"&&<section className="card"><span className="eyebrow">CUSTOMER FEEDBACK</span><h2 className="text-xl font-bold">Verified reviews</h2>{reviews.length?<div className="list mt-4">{reviews.map((r:any)=><div key={r.id} className="rounded-xl border border-[#e9e4dc] p-3"><div className="split"><b>★ {r.restaurantRating}/5</b><span className="muted text-xs">{r.user?.profile?.name??"Customer"}</span></div><p className="mt-2 text-sm">{r.text||"No written comment"}</p>{r.restaurantReply&&<p className="muted mt-2 text-sm"><b>Your reply:</b> {r.restaurantReply}</p>}<Button variant="ghost" onClick={()=>reply(r)} style={{marginTop:8}}>Reply</Button></div>)}</div>:<EmptyState title="No reviews yet" body="Delivered-order reviews will appear here."/>}</section>}

  {tab==="Payouts"&&<section className="card"><span className="eyebrow">PAYOUT LEDGER</span><h2 className="text-xl font-bold">Restaurant settlements</h2><div className="mt-4 text-3xl font-black">{money(settlements.totalPayoutPaise??0)}</div>{settlements.entries?.length?<div className="list mt-4">{settlements.entries.map((s:any)=><div className="row" key={s.id}><div><b>{s.restaurant?.name}</b><div className="muted text-sm">{s.order?.orderNumber} · {s.status.replaceAll("_"," ")}</div></div><b>{money(s.payoutPaise)}</b></div>)}</div>:<EmptyState title="No settlements yet" body="Delivered orders create settlement entries."/>}</section>}

  {tab==="Settings"&&<section className="grid cols-2"><div className="card stack"><span className="eyebrow">STORE CONTROL</span><h2 className="text-xl font-bold">{selected?.name}</h2><div className="flex flex-wrap gap-2"><Button variant={selected?.isOpen?"secondary":"primary"} onClick={()=>settingsPatch({isOpen:!selected?.isOpen})}>{selected?.isOpen?"Close store":"Open store"}</Button><Button variant={selected?.isPaused?"primary":"secondary"} onClick={()=>settingsPatch({isPaused:!selected?.isPaused})}>{selected?.isPaused?"Resume orders":"Pause orders"}</Button><Button variant="secondary" onClick={saveHours}>Set weekly hours</Button></div><label className="text-sm">Preparation time (minutes)<input className="input mt-1" type="number" min="1" value={selected?.prepMinutes??25} onChange={e=>settingsPatch({prepMinutes:Number(e.target.value)})}/></label><label className="text-sm">Minimum order ₹<input className="input mt-1" type="number" min="0" value={(selected?.minOrderPaise??0)/100} onChange={e=>settingsPatch({minOrderPaise:Math.round(Number(e.target.value)*100)})}/></label></div><div className="card"><h2 className="text-xl font-bold">Opening hours</h2>{menu?.hours?.length?<div className="list mt-4">{menu.hours.map((h:any)=><div className="row" key={h.id}><span>Day {h.weekday}</span><b>{h.closed?"Closed":h.opensAt+" – "+h.closesAt}</b></div>)}</div>:<EmptyState title="Hours not configured" body="Set weekly hours to publish a consistent schedule."/>}</div></section>}

  {tab==="Staff"&&<section className="card max-w-xl"><span className="eyebrow">TEAM ACCESS</span><h2 className="text-xl font-bold">Add staff member</h2><p className="muted mt-1 text-sm">The staff member must create a PPM Bites account first.</p><form className="stack mt-4" onSubmit={addStaff}><input className="input" type="email" required placeholder="Staff email" value={staff.email} onChange={e=>setStaff({...staff,email:e.target.value})}/><select className="input" value={staff.role} onChange={e=>setStaff({...staff,role:e.target.value})}><option value="RESTAURANT_STAFF">Restaurant staff</option><option value="RESTAURANT_MANAGER">Restaurant manager</option></select><Button>Add access</Button></form></section>}

  {tab==="Analytics"&&<section className="grid cols-4"><Stat label="Live orders" value={active.length}/><Stat label="Reviews" value={reviews.length}/><Stat label="Avg rating" value={selected?Number(selected.avgRating).toFixed(1):"—"}/><Stat label="Payout ledger" value={money(settlements.totalPayoutPaise??0)}/></section>}
  {tab==="Support"&&<section className="card"><h2 className="text-xl font-bold">Partner support</h2><p className="muted mt-2">Use the platform support workflow for order, payout or account issues.</p></section>}
  {message&&<div className="toast">{message}</div>}
 </PortalShell>;
}

function OrderQueue({orders,transition}:{orders:any[];transition:(id:string,to:string)=>void}){
 return <section className="card"><div className="split"><div><span className="eyebrow">LIVE QUEUE</span><h2 className="text-xl font-bold">Incoming orders</h2></div><Pill tone="success">● Live</Pill></div>{orders.length?<div className="list mt-4">{orders.map(o=><div className="row" key={o.id}><div><b>{o.orderNumber}</b><div className="muted text-sm">{o.items.map((i:any)=>i.quantity+"× "+i.nameSnapshot).join(", ")}</div><div className="mt-1 font-bold">{money(o.totalPaise)}</div></div><div className="flex flex-wrap justify-end gap-2"><Pill tone="warning">{o.status.replaceAll("_"," ")}</Pill>{o.status==="PLACED"&&<Button onClick={()=>transition(o.id,"RESTAURANT_CONFIRMED")}>Accept</Button>}{o.status==="RESTAURANT_CONFIRMED"&&<Button onClick={()=>transition(o.id,"PREPARING")}>Start prep</Button>}{["PREPARING","DELIVERY_PARTNER_ASSIGNED","DELIVERY_PARTNER_ARRIVED_AT_RESTAURANT"].includes(o.status)&&<Button onClick={()=>transition(o.id,"READY_FOR_PICKUP")}>Ready</Button>}</div></div>)}</div>:<EmptyState title="No active orders" body="New orders will appear here after checkout."/>}</section>
}
function StoreStatus({restaurants}:{restaurants:any[]}){return <section className="card"><span className="eyebrow">STORE STATUS</span><h2 className="text-xl font-bold">Your restaurants</h2><div className="list mt-4">{restaurants.map(r=><div className="row" key={r.id}><div><b>{r.name}</b><div className="muted text-sm">{r.address}</div></div><Pill tone={r.status!=="APPROVED"?"warning":r.isOpen&&!r.isPaused?"success":"danger"}>{r.status!=="APPROVED"?r.status.replaceAll("_"," "):r.isPaused?"Paused":r.isOpen?"Open":"Closed"}</Pill></div>)}</div></section>}
