"use client";
import {useEffect,useMemo,useState} from "react";
import {api,Brand,Button,EmptyState,money,Pill} from "@ppm/ui";

type Restaurant={id:string;slug:string;name:string;description?:string;avgRating:string|number;ratingCount:number;prepMinutes:number;avgCostForTwoPaise:number;vegOnly:boolean;distanceKm?:number|null;estimatedDeliveryMinutes?:number|null;menuItems?:any[]};
type MenuRestaurant=Restaurant&{categories:{id:string;name:string;items:any[]}[]};

export default function CustomerApp(){
 const [token,setToken]=useState<string|null>(null),[identifier,setIdentifier]=useState("customer@ppmbites.local"),[password,setPassword]=useState("DemoPass!2026");
 const [restaurants,setRestaurants]=useState<Restaurant[]>([]),[selected,setSelected]=useState<MenuRestaurant|null>(null),[cart,setCart]=useState<any>(null),[search,setSearch]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{setToken(sessionStorage.getItem("ppm_access_token"));if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});},[]);
 useEffect(()=>{loadRestaurants()},[]);
 async function loadRestaurants(){try{const d:any=await api("/restaurants?lat=18.783&lng=83.426&search="+encodeURIComponent(search));setRestaurants(d.items??[])}catch(e:any){setMessage(e.message)}}
 async function login(e:React.FormEvent){e.preventDefault();try{const d:any=await api("/auth/login",{method:"POST",body:JSON.stringify({identifier,password})});sessionStorage.setItem("ppm_access_token",d.accessToken);setToken(d.accessToken);setMessage("Signed in")}catch(e:any){setMessage(e.message)}}
 async function openRestaurant(slug:string){try{const r:any=await api("/restaurants/"+slug);setSelected(r);if(token){const c=await api("/carts/"+r.id);setCart(c)}}catch(e:any){setMessage(e.message)}}
 async function add(item:any){if(!token){setMessage("Sign in to add items");return}try{const c:any=await api("/carts/"+selected!.id+"/items",{method:"PUT",body:JSON.stringify({menuItemId:item.id,quantity:1,addonIds:[]})});setCart(c);setMessage(item.name+" added")}catch(e:any){setMessage(e.message)}}
 const cartTotal=useMemo(()=>cart?.items?.reduce((s:number,i:any)=>s+(i.menuItem.discountedPricePaise??i.menuItem.pricePaise)*i.quantity,0)??0,[cart]);

 if(selected)return <div className="min-h-screen bg-[#f8f5ef]"><div className="sticky top-0 z-20 border-b border-[#e9e4dc] bg-[#fffdfa]/95 p-4 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between"><button onClick={()=>setSelected(null)} className="font-semibold">← Back</button><Brand/><span>{cart?.items?.length??0} items</span></div></div><main className="mx-auto max-w-6xl p-4 md:p-7"><div className="card mb-5"><div className="split"><div><span className="eyebrow">RESTAURANT</span><h1 className="text-3xl font-bold">{selected.name}</h1><p className="muted">{selected.description}</p><div className="flex gap-2"><Pill tone="success">★ {Number(selected.avgRating).toFixed(1)}</Pill><Pill>{selected.prepMinutes} min</Pill></div></div><div className="text-right"><div className="text-2xl font-bold">{money(selected.avgCostForTwoPaise)}</div><span className="muted">for two</span></div></div></div>{selected.categories.map(cat=><section key={cat.id} className="card mb-4"><h2 className="mb-3 text-xl font-bold">{cat.name}</h2><div className="list">{cat.items.map(item=><div className="row" key={item.id}><div><div className="font-bold">{item.veg?"🟢":"🔴"} {item.name} {item.bestseller&&<Pill tone="warning">Bestseller</Pill>}</div><div>{money(item.discountedPricePaise??item.pricePaise)}</div><p className="muted max-w-xl text-sm">{item.description}</p></div><Button onClick={()=>add(item)}>Add</Button></div>)}</div></section>)}</main>{cartTotal>0&&<div className="fixed bottom-4 left-1/2 z-30 flex w-[calc(100%-32px)] max-w-xl -translate-x-1/2 items-center justify-between rounded-2xl bg-[#171512] p-3 text-white shadow-2xl"><div><b>{cart.items.length} item(s)</b><div>{money(cartTotal)}</div></div><a className="rounded-xl bg-[#e6502c] px-5 py-3 font-bold" href="/checkout">View cart →</a></div>}{message&&<div className="toast">{message}</div>}</div>;

 return <div className="min-h-screen bg-[#f8f5ef]">
   <header className="sticky top-0 z-20 border-b border-[#e9e4dc] bg-[#fffdfa]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 p-4"><Brand/><div className="hidden text-sm md:block">📍 Parvathipuram Central</div>{token?<Button variant="secondary" onClick={()=>{sessionStorage.removeItem("ppm_access_token");setToken(null)}}>Sign out</Button>:<span className="text-sm font-semibold">Guest</span>}</div></header>
   <main className="mx-auto max-w-7xl p-4 md:p-7">
    <section className="mb-7 grid gap-5 rounded-[28px] bg-[#171512] p-6 text-white md:grid-cols-[1.4fr_.6fr] md:p-10"><div><span className="eyebrow">PARVATHIPURAM'S OWN</span><h1 className="mt-2 text-4xl font-black leading-tight md:text-6xl">Good food.<br/>Closer to home.</h1><p className="mt-3 max-w-xl text-[#cfc8bf]">Discover local restaurants, transparent pricing and live delivery progress in one original experience.</p></div>{!token&&<form onSubmit={login} className="rounded-2xl bg-white p-4 text-[#171512]"><h2 className="mb-3 text-lg font-bold">Demo sign in</h2><div className="stack"><input className="input" value={identifier} onChange={e=>setIdentifier(e.target.value)} aria-label="Email or phone"/><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} aria-label="Password"/><Button type="submit">Sign in</Button></div></form>}</section>
    <div className="mb-5 flex gap-2"><input className="input" placeholder="Search restaurants, dishes or cuisine" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&loadRestaurants()}/><Button onClick={loadRestaurants}>Search</Button></div>
    <div className="mb-4 flex gap-2 overflow-auto pb-1"><Pill>Fast delivery</Pill><Pill>Top rated</Pill><Pill>Veg</Pill><Pill>Offers</Pill><Pill>Budget friendly</Pill></div>
    <h2 className="mb-4 text-2xl font-bold">Restaurants near you</h2>
    {restaurants.length?<div className="grid cols-3">{restaurants.map(r=><button key={r.id} onClick={()=>openRestaurant(r.slug)} className="card text-left transition hover:-translate-y-1"><div className="mb-4 h-36 rounded-2xl bg-gradient-to-br from-[#ffdfc7] to-[#f39e75] p-4"><span className="pill">{r.vegOnly?"Pure veg":"Multi-cuisine"}</span></div><div className="split"><h3 className="text-lg font-bold">{r.name}</h3><Pill tone="success">★ {Number(r.avgRating).toFixed(1)}</Pill></div><p className="muted mt-1 line-clamp-2 text-sm">{r.description}</p><div className="mt-4 flex justify-between text-sm"><span>{r.estimatedDeliveryMinutes??r.prepMinutes} min</span><span>{money(r.avgCostForTwoPaise)} for two</span></div></button>)}</div>:<EmptyState title="No restaurants found" body="Try a broader search or another location."/>}
   </main>{message&&<div className="toast">{message}</div>}
 </div>
}
