"use client";
import {useEffect,useMemo,useState} from "react";
import {api,Brand,Button,clearSession,EmptyState,money,Pill,saveSession} from "@ppm/ui";

type Restaurant={id:string;slug:string;name:string;description?:string;avgRating:string|number;ratingCount:number;prepMinutes:number;avgCostForTwoPaise:number;vegOnly:boolean;distanceKm?:number|null;estimatedDeliveryMinutes?:number|null};
type MenuRestaurant=Restaurant&{categories:{id:string;name:string;items:any[]}[]};
type Capabilities={passwordAuth:boolean;cod:boolean;onlinePayments:boolean;smsOtp:boolean;emailOtp:boolean};

export default function CustomerApp(){
 const [token,setToken]=useState<string|null>(null);
 const [authMode,setAuthMode]=useState<"login"|"signup"|"forgot"|"reset">("login");
 const [identifier,setIdentifier]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState(""),[resetCode,setResetCode]=useState(""),[newPassword,setNewPassword]=useState("");
 const [capabilities,setCapabilities]=useState<Capabilities>({passwordAuth:true,cod:true,onlinePayments:false,smsOtp:false,emailOtp:false});
 const [restaurants,setRestaurants]=useState<Restaurant[]>([]),[selected,setSelected]=useState<MenuRestaurant|null>(null),[cart,setCart]=useState<any>(null),[search,setSearch]=useState(""),[message,setMessage]=useState("");

 useEffect(()=>{
   setToken(sessionStorage.getItem("ppm_access_token"));
   api<Capabilities>("/platform/capabilities").then(setCapabilities).catch(()=>{});
   if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
 },[]);
 useEffect(()=>{loadRestaurants()},[]);

 async function loadRestaurants(){try{const d:any=await api("/restaurants?lat=18.783&lng=83.426&search="+encodeURIComponent(search));setRestaurants(d.items??[])}catch(e:any){setMessage(e.message)}}
 async function login(e:React.FormEvent){e.preventDefault();try{const d:any=await api("/auth/login",{method:"POST",body:JSON.stringify({identifier,password})});saveSession(d);setToken(d.accessToken);setPassword("");setMessage("Signed in successfully")}catch(e:any){setMessage(e.message)}}
 async function signup(e:React.FormEvent){e.preventDefault();try{
   const r:any=await api("/auth/register",{method:"POST",body:JSON.stringify({name,email,password})});
   const d:any=await api("/auth/login",{method:"POST",body:JSON.stringify({identifier:email,password})});
   saveSession(d);setToken(d.accessToken);setMessage(r.verificationRequired?"Account created. A verification code was sent to your email.":"Account created successfully");
 }catch(e:any){setMessage(e.message)}}
 async function forgot(e:React.FormEvent){e.preventDefault();try{await api("/auth/forgot-password",{method:"POST",body:JSON.stringify({identifier})});setAuthMode("reset");setMessage("If the account exists, a reset code was sent.")}catch(e:any){setMessage(e.message)}}
 async function reset(e:React.FormEvent){e.preventDefault();try{await api("/auth/reset-password",{method:"POST",body:JSON.stringify({identifier,code:resetCode,newPassword})});setPassword("");setAuthMode("login");setMessage("Password reset. Sign in with your new password.")}catch(e:any){setMessage(e.message)}}
 async function openRestaurant(slug:string){try{const r:any=await api("/restaurants/"+slug);setSelected(r);sessionStorage.setItem("ppm_restaurant_id",r.id);if(token){const c=await api("/carts/"+r.id);setCart(c)}}catch(e:any){setMessage(e.message)}}
 async function add(item:any){if(!token){setSelected(null);setAuthMode("login");setMessage("Sign in to add items");return}try{const c:any=await api("/carts/"+selected!.id+"/items",{method:"PUT",body:JSON.stringify({menuItemId:item.id,quantity:1,addonIds:[]})});setCart(c);setMessage(item.name+" added")}catch(e:any){setMessage(e.message)}}
 const cartTotal=useMemo(()=>cart?.items?.reduce((s:number,i:any)=>s+(i.menuItem.discountedPricePaise??i.menuItem.pricePaise)*i.quantity,0)??0,[cart]);
 const recoveryAvailable=identifier.includes("@")?capabilities.emailOtp:capabilities.smsOtp;

 if(selected)return <div className="min-h-screen bg-[#f8f5ef]"><div className="sticky top-0 z-20 border-b border-[#e9e4dc] bg-[#fffdfa]/95 p-4 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between"><button onClick={()=>setSelected(null)} className="font-semibold">← Back</button><Brand/><span>{cart?.items?.length??0} items</span></div></div><main className="mx-auto max-w-6xl p-4 md:p-7"><div className="card mb-5"><div className="split"><div><span className="eyebrow">RESTAURANT</span><h1 className="text-3xl font-bold">{selected.name}</h1><p className="muted">{selected.description}</p><div className="flex gap-2"><Pill tone="success">★ {Number(selected.avgRating).toFixed(1)}</Pill><Pill>{selected.prepMinutes} min</Pill></div></div><div className="text-right"><div className="text-2xl font-bold">{money(selected.avgCostForTwoPaise)}</div><span className="muted">for two</span></div></div></div>{selected.categories.map(cat=><section key={cat.id} className="card mb-4"><h2 className="mb-3 text-xl font-bold">{cat.name}</h2><div className="list">{cat.items.map(item=><div className="row" key={item.id}><div><div className="font-bold">{item.veg?"🟢":"🔴"} {item.name} {item.bestseller&&<Pill tone="warning">Bestseller</Pill>}</div><div>{money(item.discountedPricePaise??item.pricePaise)}</div><p className="muted max-w-xl text-sm">{item.description}</p></div><Button onClick={()=>add(item)}>Add</Button></div>)}</div></section>)}</main>{cartTotal>0&&<div className="fixed bottom-4 left-1/2 z-30 flex w-[calc(100%-32px)] max-w-xl -translate-x-1/2 items-center justify-between rounded-2xl bg-[#171512] p-3 text-white shadow-2xl"><div><b>{cart.items.length} item(s)</b><div>{money(cartTotal)}</div></div><a className="rounded-xl bg-[#e6502c] px-5 py-3 font-bold" href="/checkout">View cart →</a></div>}{message&&<div className="toast">{message}</div>}</div>;

 return <div className="min-h-screen bg-[#f8f5ef]">
  <header className="sticky top-0 z-20 border-b border-[#e9e4dc] bg-[#fffdfa]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 p-4"><Brand/><div className="hidden text-sm md:block">📍 Parvathipuram Central</div>{token?<div className="flex gap-2"><a className="button ghost inline-flex items-center" href="/orders">Orders</a><Button variant="secondary" onClick={()=>{clearSession();setToken(null);setCart(null)}}>Sign out</Button></div>:<span className="text-sm font-semibold">Guest</span>}</div></header>
  <main className="mx-auto max-w-7xl p-4 md:p-7">
   <section className="mb-7 grid gap-5 rounded-[28px] bg-[#171512] p-6 text-white md:grid-cols-[1.4fr_.6fr] md:p-10"><div><span className="eyebrow">PARVATHIPURAM'S OWN</span><h1 className="mt-2 text-4xl font-black leading-tight md:text-6xl">Good food.<br/>Closer to home.</h1><p className="mt-3 max-w-xl text-[#cfc8bf]">Discover local restaurants, transparent pricing and live delivery progress in one original experience.</p><div className="mt-5 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-white/10 px-3 py-2">COD available</span><span className="rounded-full bg-white/10 px-3 py-2">{capabilities.onlinePayments?"Online payments enabled":"Online payments coming soon"}</span></div></div>
   {!token&&<div className="rounded-2xl bg-white p-4 text-[#171512]"><div className="mb-4 flex gap-2"><button className={"pill "+(authMode==="login"?"success":"")} onClick={()=>setAuthMode("login")}>Sign in</button><button className={"pill "+(authMode==="signup"?"success":"")} onClick={()=>setAuthMode("signup")}>Create account</button></div>
    {authMode==="login"&&<form onSubmit={login} className="stack"><h2 className="text-lg font-bold">Welcome back</h2><input className="input" placeholder="Email or phone" value={identifier} onChange={e=>setIdentifier(e.target.value)} required/><input className="input" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit">Sign in</Button><button type="button" className="text-left text-sm font-semibold text-[#b83317]" onClick={()=>setAuthMode("forgot")}>Forgot password?</button></form>}
    {authMode==="signup"&&<form onSubmit={signup} className="stack"><h2 className="text-lg font-bold">Create your account</h2><input className="input" placeholder="Your name" value={name} onChange={e=>setName(e.target.value)} required/><input className="input" type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input className="input" type="password" minLength={10} placeholder="Password (10+ characters)" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit">Create account</Button></form>}
    {authMode==="forgot"&&<form onSubmit={forgot} className="stack"><h2 className="text-lg font-bold">Reset password</h2><input className="input" placeholder="Email or phone" value={identifier} onChange={e=>setIdentifier(e.target.value)} required/><p className="muted text-sm">{recoveryAvailable?"We will send a 6-digit reset code.":"Recovery delivery is not configured yet. You can still sign in with your password."}</p><Button type="submit" disabled={!recoveryAvailable}>Send reset code</Button><button type="button" className="text-left text-sm font-semibold" onClick={()=>setAuthMode("login")}>Back to sign in</button></form>}
    {authMode==="reset"&&<form onSubmit={reset} className="stack"><h2 className="text-lg font-bold">Enter reset code</h2><input className="input" inputMode="numeric" maxLength={6} placeholder="6-digit code" value={resetCode} onChange={e=>setResetCode(e.target.value.replace(/\D/g,""))} required/><input className="input" type="password" minLength={10} placeholder="New password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} required/><Button type="submit">Set new password</Button></form>}
   </div>}</section>
   <div className="mb-5 flex gap-2"><input className="input" placeholder="Search restaurants, dishes or cuisine" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&loadRestaurants()}/><Button onClick={loadRestaurants}>Search</Button></div>
   <div className="mb-4 flex gap-2 overflow-auto pb-1"><Pill>Fast delivery</Pill><Pill>Top rated</Pill><Pill>Veg</Pill><Pill>Offers</Pill><Pill>Budget friendly</Pill></div>
   <h2 className="mb-4 text-2xl font-bold">Restaurants near you</h2>
   {restaurants.length?<div className="grid cols-3">{restaurants.map(r=><button key={r.id} onClick={()=>openRestaurant(r.slug)} className="card text-left transition hover:-translate-y-1"><div className="mb-4 h-36 rounded-2xl bg-gradient-to-br from-[#ffdfc7] to-[#f39e75] p-4"><span className="pill">{r.vegOnly?"Pure veg":"Multi-cuisine"}</span></div><div className="split"><h3 className="text-lg font-bold">{r.name}</h3><Pill tone="success">★ {Number(r.avgRating).toFixed(1)}</Pill></div><p className="muted mt-1 line-clamp-2 text-sm">{r.description}</p><div className="mt-4 flex justify-between text-sm"><span>{r.estimatedDeliveryMinutes??r.prepMinutes} min</span><span>{money(r.avgCostForTwoPaise)} for two</span></div></button>)}</div>:<EmptyState title="No restaurants found" body="Try a broader search or another location."/>}
  </main>{message&&<div className="toast">{message}</div>}
 </div>;
}
