"use client";
import {useEffect,useMemo,useState} from "react";
import {api,Brand,Button,EmptyState,money,Pill,clearSession} from "@ppm/ui";

type Restaurant={id:string;slug:string;name:string;description?:string;avgRating:string|number;ratingCount:number;prepMinutes:number;avgCostForTwoPaise:number;vegOnly:boolean;distanceKm?:number|null;estimatedDeliveryMinutes?:number|null;menuItems?:any[]};
type MenuRestaurant=Restaurant&{categories:{id:string;name:string;items:any[]}[]};
const localDirectory=[
 {name:"Zaikas Green Chutneys",category:"South Indian"},
 {name:"Apna Darbar",category:"North Indian · Biryani"},
 {name:"Delicious Fried Chicken",category:"Fast food · Pizza · Burgers"},
 {name:"Mana Inti Kitchen",category:"Wraps · Sandwiches · Fast food"},
 {name:"Madhuram Authentic Telugu Kitchen",category:"Telugu · South Indian · Biryani"},
 {name:"Taj Royal Food Street",category:"Andhra · South Indian"},
 {name:"Biryanis And More",category:"Biryani · Kebab · Chinese"},
 {name:"Helapuri Multicuisine Resturant",category:"Biryani · Chinese · Andhra"}
];
const groceryDirectory=[{name:"More Supermarket",category:"Groceries · Supermarket"}];

export default function CustomerApp(){
 const [token,setToken]=useState<string|null>(null);
 const [restaurants,setRestaurants]=useState<Restaurant[]>([]),[selected,setSelected]=useState<MenuRestaurant|null>(null),[cart,setCart]=useState<any>(null),[search,setSearch]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{setToken(sessionStorage.getItem("ppm_access_token"));if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});},[]);
 useEffect(()=>{loadRestaurants()},[]);
 useEffect(()=>{const slug=new URLSearchParams(location.search).get("restaurant");if(slug)openRestaurant(slug)},[token]);
 async function loadRestaurants(){try{const d:any=await api("/restaurants?lat=18.783&lng=83.426&search="+encodeURIComponent(search));setRestaurants(d.items??[])}catch(e:any){setMessage(e.message)}}
 async function openRestaurant(slug:string){try{const r:any=await api("/restaurants/"+slug);setSelected(r);sessionStorage.setItem("ppm_restaurant_id",r.id);if(token){const c=await api("/carts/"+r.id);setCart(c)}}catch(e:any){setMessage(e.message)}}
 async function add(item:any){if(!token){location.href="/account";return}try{const c:any=await api("/carts/"+selected!.id+"/items",{method:"PUT",body:JSON.stringify({menuItemId:item.id,quantity:1,addonIds:[]})});setCart(c);setMessage(item.name+" added")}catch(e:any){setMessage(e.message)}}
 async function saveRestaurant(){if(!token){location.href="/account";return}try{await api("/favorites/restaurants/"+selected!.id,{method:"POST"});setMessage(selected!.name+" saved to Favorites")}catch(e:any){setMessage(e.message)}}
 async function saveDish(item:any){if(!token){location.href="/account";return}try{await api("/favorites/dishes/"+item.id,{method:"POST"});setMessage(item.name+" saved to Favorites")}catch(e:any){setMessage(e.message)}}
 const cartTotal=useMemo(()=>cart?.items?.reduce((s:number,i:any)=>s+(i.menuItem.discountedPricePaise??i.menuItem.pricePaise)*i.quantity,0)??0,[cart]);
 function signOut(){clearSession();setToken(null);setCart(null)}

 if(selected)return <div className="min-h-screen bg-[#f8f5ef]"><div className="sticky top-0 z-20 border-b border-[#e9e4dc] bg-[#fffdfa]/95 p-4 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between"><button onClick={()=>setSelected(null)} className="font-semibold">← Back</button><Brand/><span>{cart?.items?.length??0} items</span></div></div><main className="mx-auto max-w-6xl p-4 md:p-7"><div className="card mb-5"><div className="split"><div><span className="eyebrow">RESTAURANT</span><h1 className="text-3xl font-bold">{selected.name}</h1><p className="muted">{selected.description}</p><div className="flex gap-2"><Pill tone="success">★ {Number(selected.avgRating).toFixed(1)}</Pill><Pill>{selected.prepMinutes} min</Pill></div></div><div className="text-right"><div className="text-2xl font-bold">{money(selected.avgCostForTwoPaise)}</div><span className="muted">for two</span><div className="mt-3"><Button variant="secondary" onClick={saveRestaurant}>♡ Save restaurant</Button></div></div></div></div>{selected.categories.map(cat=><section key={cat.id} className="card mb-4"><h2 className="mb-3 text-xl font-bold">{cat.name}</h2><div className="list">{cat.items.map(item=><div className="row" key={item.id}><div><div className="font-bold">{item.veg?"🟢":"🔴"} {item.name} {item.bestseller&&<Pill tone="warning">Bestseller</Pill>}</div><div>{money(item.discountedPricePaise??item.pricePaise)}</div><p className="muted max-w-xl text-sm">{item.description}</p></div><div className="flex gap-2"><Button variant="ghost" onClick={()=>saveDish(item)}>♡</Button><Button onClick={()=>add(item)}>Add</Button></div></div>)}</div></section>)}</main>{cartTotal>0&&<div className="fixed bottom-4 left-1/2 z-30 flex w-[calc(100%-32px)] max-w-xl -translate-x-1/2 items-center justify-between rounded-2xl bg-[#171512] p-3 text-white shadow-2xl"><div><b>{cart.items.length} item(s)</b><div>{money(cartTotal)}</div></div><a className="rounded-xl bg-[#e6502c] px-5 py-3 font-bold" href="/checkout">View cart →</a></div>}{message&&<div className="toast">{message}</div>}</div>;

 return <div className="min-h-screen bg-[#f8f5ef]">
   <header className="sticky top-0 z-20 border-b border-[#e9e4dc] bg-[#fffdfa]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 p-4"><Brand/><div className="hidden text-sm md:block">📍 Parvathipuram Central</div><div className="flex items-center gap-2">{token&&<a href="/orders" className="button ghost inline-flex items-center">Orders</a>}{token&&<a href="/favorites" className="button ghost inline-flex items-center">Favorites</a>}<a href="/account" className="button secondary inline-flex items-center">{token?"Account":"Sign in"}</a>{token&&<Button variant="ghost" onClick={signOut}>Sign out</Button>}</div></div></header>
   <main className="mx-auto max-w-7xl p-4 md:p-7">
    <section className="mb-7 grid gap-5 overflow-hidden rounded-[28px] bg-[#171512] p-6 text-white md:grid-cols-[1.3fr_.7fr] md:p-10"><div><span className="eyebrow">PARVATHIPURAM'S OWN</span><h1 className="mt-2 text-4xl font-black leading-tight md:text-6xl">Local favourites.<br/>Delivered simply.</h1><p className="mt-3 max-w-xl text-[#cfc8bf]">Order food from nearby restaurants with transparent pricing, secure accounts and live order progress.</p><div className="mt-5 flex flex-wrap gap-2"><Pill tone="success">Local restaurants</Pill><Pill>Live tracking</Pill><Pill>Cash on delivery</Pill></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-3xl bg-[#e6502c] p-5"><div className="text-4xl">🍛</div><b className="mt-6 block text-xl">Meals & biryani</b><span className="text-sm text-[#ffe1d9]">Fresh local picks</span></div><div className="rounded-3xl bg-[#f2b84b] p-5 text-[#171512]"><div className="text-4xl">⚡</div><b className="mt-6 block text-xl">Quick delivery</b><span className="text-sm">Built for Parvathipuram</span></div><div className="col-span-2 rounded-3xl bg-[#2b6f55] p-5"><div className="flex items-end justify-between"><div><div className="text-4xl">🛒</div><b className="mt-3 block text-xl">Instant groceries</b><span className="text-sm text-[#d8efe5]">Groceries section is ready for local merchant onboarding</span></div><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold">COMING ONLINE</span></div></div></div></section>
    <div className="mb-5 flex gap-2"><input className="input" placeholder="Search restaurants, dishes or cuisine" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&loadRestaurants()}/><Button onClick={loadRestaurants}>Search</Button></div>
    <div className="mb-4 flex gap-2 overflow-auto pb-1"><Pill>Fast delivery</Pill><Pill>Top rated</Pill><Pill>Veg</Pill><Pill>Offers</Pill><Pill>Budget friendly</Pill></div>
    <h2 className="mb-4 text-2xl font-bold">Restaurants near you</h2>
    {restaurants.length?<div className="grid cols-3">{restaurants.map(r=><button key={r.id} onClick={()=>openRestaurant(r.slug)} className="card text-left transition hover:-translate-y-1"><div className="mb-4 flex h-36 items-end rounded-2xl bg-gradient-to-br from-[#ffdfc7] via-[#f7b98d] to-[#e6502c] p-4"><span className="pill">{r.vegOnly?"Pure veg":"Multi-cuisine"}</span></div><div className="split"><h3 className="text-lg font-bold">{r.name}</h3><Pill tone="success">★ {Number(r.avgRating).toFixed(1)}</Pill></div><p className="muted mt-1 line-clamp-2 text-sm">{r.description}</p><div className="mt-4 flex justify-between text-sm"><span>{r.estimatedDeliveryMinutes??r.prepMinutes} min</span><span>{money(r.avgCostForTwoPaise)} for two</span></div></button>)}</div>:<EmptyState title="No restaurants found" body="Try a broader search or another location."/>}
    <section className="mt-8"><div className="split mb-4"><div><span className="eyebrow">LOCAL DIRECTORY</span><h2 className="mt-1 text-2xl font-bold">More places in Parvathipuram</h2><p className="muted text-sm">Public directory listings only. Ordering activates only after the business completes PPM Bites partner onboarding.</p></div></div><div className="grid cols-3">{localDirectory.map(x=><div key={x.name} className="card"><div className="mb-3 flex h-24 items-center justify-center rounded-2xl bg-[#f3eee7] text-4xl">🍽️</div><h3 className="font-bold">{x.name}</h3><p className="muted mt-1 text-sm">{x.category}</p><div className="mt-4"><Pill tone="warning">Not yet orderable</Pill></div></div>)}</div></section>
    <section className="mt-8 rounded-[28px] bg-[#e8f4ee] p-6 md:p-8"><div className="split"><div><span className="eyebrow">INSTANT GROCERIES</span><h2 className="mt-1 text-2xl font-black">Local grocery delivery</h2><p className="muted mt-1">The grocery vertical is separated from restaurant ordering and is onboarding local stores.</p><div className="mt-4 flex flex-wrap gap-2">{groceryDirectory.map(x=><span key={x.name} className="pill">{x.name} · onboarding pending</span>)}</div></div><a href="/partner" className="button secondary inline-flex items-center">Join as a local partner</a></div></section>
    <section className="mt-8 rounded-[28px] border border-[#e9e4dc] bg-white p-6 md:p-8"><div className="split"><div><span className="eyebrow">GROW WITH PPM BITES</span><h2 className="mt-1 text-2xl font-black">Own a restaurant or want to deliver?</h2><p className="muted mt-1">Apply directly online. Partner applications are reviewed before going live.</p></div><a href="/partner" className="button primary inline-flex items-center">Partner with us →</a></div></section>
   </main>{message&&<div className="toast">{message}</div>}
 </div>
}
