"use client";
import {useEffect,useState} from "react";
import {api,Button,clearSession,EmptyState,money,Pill,PortalShell,saveSession,Stat} from "@ppm/ui";

export default function DeliveryPortal(){
 const [logged,setLogged]=useState(false),[identifier,setIdentifier]=useState(""),[password,setPassword]=useState("");
 const [profile,setProfile]=useState<any>(null),[online,setOnline]=useState(false),[offers,setOffers]=useState<any[]>([]),[current,setCurrent]=useState<any[]>([]),[earnings,setEarnings]=useState<any>({todayPaise:0,totalPaise:0,entries:[]}),[message,setMessage]=useState("");
 useEffect(()=>setLogged(!!sessionStorage.getItem("ppm_access_token")),[]);
 useEffect(()=>{if(logged)load()},[logged]);

 async function login(e:React.FormEvent){e.preventDefault();try{const d:any=await api("/auth/login",{method:"POST",body:JSON.stringify({identifier,password})});saveSession(d);setLogged(true);setPassword("")}catch(e:any){setMessage(e.message)}}
 async function load(){
   try{
     const p:any=await api("/delivery/profile");setProfile(p);setOnline(!!p.online);
     if(p.status!=="APPROVED"){setOffers([]);setCurrent([]);setEarnings({todayPaise:0,totalPaise:0,entries:[]});return}
     const [o,c,e]:any=await Promise.all([api("/delivery/offers"),api("/delivery/current"),api("/delivery/earnings?days=7")]);
     setOffers(o);setCurrent(c);setEarnings(e);sendLocation();
   }catch(e:any){setMessage(e.message)}
 }
 async function toggle(){try{const next=!online;await api("/delivery/online",{method:"POST",body:JSON.stringify({online:next})});setOnline(next)}catch(e:any){setMessage(e.message)}}
 function sendLocation(){if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(async p=>{try{await api("/delivery/location",{method:"POST",body:JSON.stringify({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracyM:p.coords.accuracy})})}catch{}},()=>{})}
 async function respond(id:string,accept:boolean){try{await api("/delivery/assignments/"+id+"/respond",{method:"POST",body:JSON.stringify({accept})});setMessage(accept?"Delivery accepted":"Offer declined");await load()}catch(e:any){setMessage(e.message)}}
 async function advance(orderId:string,status:string){try{await api("/orders/"+orderId+"/transition",{method:"POST",body:JSON.stringify({to:status})});await load()}catch(e:any){setMessage(e.message)}}

 if(!logged)return <main className="mx-auto max-w-md p-5 pt-20"><div className="card"><span className="eyebrow">DELIVERY PARTNER</span><h1 className="my-3 text-3xl font-black">Your route. Your earnings.</h1><p className="muted">Sign in with your delivery-partner account.</p><form className="stack mt-5" onSubmit={login}><input className="input" placeholder="Partner email or phone" value={identifier} onChange={e=>setIdentifier(e.target.value)} required/><input className="input" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit">Sign in</Button></form><a href={(process.env.NEXT_PUBLIC_CUSTOMER_URL??"https://parvathipuram-food-delivery-git-production.up.railway.app")+"/partner"} className="mt-4 block text-sm font-semibold">Apply as a delivery partner →</a></div>{message&&<div className="toast">{message}</div>}</main>;

 if(profile&&profile.status!=="APPROVED")return <PortalShell title="Delivery application" nav={["Home","Profile","Support"]} active="Home" actions={<Button variant="ghost" onClick={()=>{clearSession();setLogged(false);setProfile(null)}}>Sign out</Button>}>
   <section className="card max-w-2xl"><Pill tone={profile.status==="REJECTED"?"danger":"warning"}>{String(profile.status).replaceAll("_"," ")}</Pill><h2 className="mt-4 text-2xl font-black">{profile.status==="REJECTED"?"Application needs attention":"Verification in progress"}</h2><p className="muted mt-2">You cannot go online or accept deliveries until an administrator approves your delivery-partner profile.</p><div className="mt-5 grid cols-2"><div><span className="muted text-sm">Vehicle</span><div className="font-bold">{profile.vehicleType??"Not provided"}</div></div><div><span className="muted text-sm">Vehicle number</span><div className="font-bold">{profile.vehicleNumber??"Not provided"}</div></div></div><Button variant="secondary" onClick={load} style={{marginTop:20}}>Refresh status</Button></section>{message&&<div className="toast">{message}</div>}
 </PortalShell>;

 return <PortalShell title="Delivery hub" nav={["Home","Current Delivery","Earnings","History","Profile","Support"]} active="Home" actions={<div className="flex gap-2"><Button variant={online?"secondary":"primary"} onClick={toggle}>{online?"Go offline":"Go online"}</Button><Button variant="ghost" onClick={()=>{clearSession();setLogged(false);setProfile(null)}}>Sign out</Button></div>}>
  <div className="grid cols-4 mb-5"><Stat label="Status" value={online?"Online":"Offline"} detail="Availability"/><Stat label="New offers" value={offers.length}/><Stat label="Today's earnings" value={money(earnings.todayPaise??0)}/><Stat label="7-day earnings" value={money(earnings.totalPaise??0)}/></div>
  <section className="card mb-5"><div><span className="eyebrow">CURRENT DELIVERY</span><h2 className="text-xl font-bold">Active delivery</h2></div>{current.length?<div className="list mt-4">{current.map(a=><div className="row" key={a.id}><div><b>{a.order.restaurant.name}</b><div className="muted text-sm">{a.order.restaurant.address}</div><Pill tone="warning">{a.order.status.replaceAll("_"," ")}</Pill></div><div className="flex flex-wrap gap-2">{a.order.status==="DELIVERY_PARTNER_ASSIGNED"&&<Button onClick={()=>advance(a.order.id,"DELIVERY_PARTNER_ARRIVED_AT_RESTAURANT")}>At restaurant</Button>}{["DELIVERY_PARTNER_ARRIVED_AT_RESTAURANT","READY_FOR_PICKUP"].includes(a.order.status)&&<Button onClick={()=>advance(a.order.id,"PICKED_UP")}>Picked up</Button>}{a.order.status==="PICKED_UP"&&<Button onClick={()=>advance(a.order.id,"ON_THE_WAY")}>On the way</Button>}{a.order.status==="ON_THE_WAY"&&<Button onClick={()=>advance(a.order.id,"ARRIVED_AT_CUSTOMER")}>At customer</Button>}{a.order.status==="ARRIVED_AT_CUSTOMER"&&<Button onClick={()=>advance(a.order.id,"DELIVERED")}>Delivered</Button>}</div></div>)}</div>:<EmptyState title="No active delivery" body="Accept a nearby offer to start a delivery."/>}</section>
  <div className="grid cols-2"><section className="card"><div className="split"><div><span className="eyebrow">NEARBY REQUESTS</span><h2 className="text-xl font-bold">Delivery offers</h2></div><Button variant="secondary" onClick={load}>Refresh</Button></div>{offers.length?<div className="list mt-4">{offers.map(a=><div className="row" key={a.id}><div><b>{a.order.restaurant.name}</b><div className="muted text-sm">{a.order.restaurant.address}</div><div className="mt-1 font-bold">{money(a.order.deliveryFeePaise)}</div></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>respond(a.id,false)}>Decline</Button><Button onClick={()=>respond(a.id,true)}>Accept</Button></div></div>)}</div>:<EmptyState title={online?"No delivery offers right now":"You are offline"} body={online?"Nearby requests will appear here when restaurants need a rider.":"Go online to receive delivery requests."}/>}</section>
  <section className="card"><span className="eyebrow">EARNINGS</span><h2 className="text-xl font-bold">Recent earnings</h2>{earnings.entries?.length?<div className="list mt-4">{earnings.entries.slice(0,10).map((e:any)=><div className="row" key={e.id}><div><b>{new Date(e.createdAt).toLocaleDateString()}</b><div className="muted text-sm">{e.settlementStatus.replaceAll("_"," ")}</div></div><b>{money(e.totalPaise)}</b></div>)}</div>:<EmptyState title="No earnings yet" body="Completed deliveries will appear here automatically."/>}</section></div>{message&&<div className="toast">{message}</div>}
 </PortalShell>;
}
