"use client";
import {useEffect,useState} from "react";
import {api,Button,clearSession,EmptyState,money,Pill,PortalShell,saveSession,Stat} from "@ppm/ui";

type Tab="Dashboard"|"Orders"|"Restaurants"|"Delivery Partners"|"Customers"|"Payments"|"Refunds"|"Promotions"|"Reviews"|"Finance"|"Analytics"|"Audit Logs"|"System";

export default function AdminPortal(){
 const [logged,setLogged]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState("");
 const [tab,setTab]=useState<Tab>("Dashboard"),[kpi,setKpi]=useState<any>(null),[pendingRestaurants,setPendingRestaurants]=useState<any[]>([]),[pendingRiders,setPendingRiders]=useState<any[]>([]);
 const [data,setData]=useState<any>(null),[integrations,setIntegrations]=useState<any>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const nav:Tab[]=["Dashboard","Orders","Restaurants","Delivery Partners","Customers","Payments","Refunds","Promotions","Reviews","Finance","Analytics","Audit Logs","System"];

 useEffect(()=>setLogged(!!sessionStorage.getItem("ppm_access_token")),[]);
 useEffect(()=>{if(logged){loadBase();loadTab(tab)}},[logged]);
 useEffect(()=>{if(logged)loadTab(tab)},[tab]);

 async function login(e:React.FormEvent){e.preventDefault();try{const d:any=await api("/auth/login",{method:"POST",body:JSON.stringify({identifier:email,password})});saveSession(d);setLogged(true);setPassword("")}catch(e:any){setMessage(e.message)}}
 async function loadBase(){try{const [a,b,c]:any=await Promise.all([api("/admin/kpis"),api("/admin/restaurants/pending"),api("/admin/delivery-partners/pending")]);setKpi(a);setPendingRestaurants(b);setPendingRiders(c)}catch(e:any){setMessage(e.message)}}
 async function loadTab(next:Tab){
   try{
     if(next==="Dashboard"){setData(null);return}
     const path:Record<Tab,string|null>={
       Dashboard:null,Orders:"/admin/orders",Restaurants:"/admin/restaurants","Delivery Partners":"/admin/delivery-partners",
       Customers:"/admin/customers",Payments:"/admin/payments",Refunds:"/admin/refunds",Promotions:"/admin/promotions",
       Reviews:"/admin/reviews",Finance:"/admin/finance",Analytics:"/admin/analytics/events?days=7","Audit Logs":"/admin/audit",
       System:"/admin/cities"
     };
     if(next==="System"){
       const [cities,status]:any=await Promise.all([api("/admin/cities"),api("/admin/integrations/status").catch(()=>null)]);
       setData(cities);setIntegrations(status);return;
     }
     if(path[next])setData(await api(path[next]!));
   }catch(e:any){setMessage(e.message)}
 }
 async function refresh(){await Promise.all([loadBase(),loadTab(tab)])}
 async function setRestaurantStatus(id:string,status:string){try{await api("/admin/restaurants/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})});await refresh()}catch(e:any){setMessage(e.message)}}
 async function setRiderStatus(id:string,status:string){try{await api("/admin/delivery-partners/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})});await refresh()}catch(e:any){setMessage(e.message)}}
 async function setCustomerStatus(id:string,status:string){const reason=prompt("Reason for "+status.toLowerCase()+"?");if(!reason)return;try{await api("/admin/customers/"+id+"/status",{method:"PATCH",body:JSON.stringify({status,reason})});await loadTab("Customers")}catch(e:any){setMessage(e.message)}}
 async function moderateReview(id:string,status:string){const reason=prompt("Moderation reason (optional)")??undefined;try{await api("/admin/reviews/"+id+"/status",{method:"PATCH",body:JSON.stringify({status,reason})});await loadTab("Reviews")}catch(e:any){setMessage(e.message)}}
 async function dispatch(orderId:string){try{await api("/delivery/dispatch/"+orderId,{method:"POST"});setMessage("Delivery offers sent to nearby riders")}catch(e:any){setMessage(e.message)}}
 async function refundOrder(order:any){const amount=Number(prompt("Refund amount in rupees",String((order.totalPaise/100).toFixed(2))));if(!amount)return;const reason=prompt("Refund reason");if(!reason)return;try{await api("/admin/refunds",{method:"POST",body:JSON.stringify({orderId:order.id,amountPaise:Math.round(amount*100),reason,idempotencyKey:"admin-"+order.id+"-"+Date.now()})});setMessage("Refund processed/queued");await loadTab("Refunds")}catch(e:any){setMessage(e.message)}}
 async function createPromotion(){const title=prompt("Promotion title");if(!title)return;const description=prompt("Description")??undefined;const days=Number(prompt("How many days should it run?","7")??7);try{await api("/admin/promotions",{method:"POST",body:JSON.stringify({title,description,kind:"FEATURED",startsAt:new Date().toISOString(),endsAt:new Date(Date.now()+Math.max(1,days)*86400000).toISOString(),active:true,sponsored:false})});await loadTab("Promotions")}catch(e:any){setMessage(e.message)}}
 async function sendCampaign(){const title=prompt("Notification title");if(!title)return;const body=prompt("Notification body");if(!body)return;const role=prompt("Audience role: CUSTOMER, RESTAURANT_OWNER, DELIVERY_PARTNER","CUSTOMER")??"CUSTOMER";try{await api("/admin/notifications/in-app",{method:"POST",body:JSON.stringify({role,title,body,type:"CAMPAIGN"})});setMessage("Campaign sent")}catch(e:any){setMessage(e.message)}}

 if(!logged)return <main className="mx-auto max-w-md p-5 pt-20"><div className="card"><span className="eyebrow">PLATFORM ADMIN</span><h1 className="my-3 text-3xl font-black">Operate with visibility</h1><form className="stack mt-5" onSubmit={login}><input className="input" type="email" placeholder="Admin email" value={email} onChange={e=>setEmail(e.target.value)} required/><input className="input" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit">Sign in</Button></form></div>{message&&<div className="toast">{message}</div>}</main>;

 return <PortalShell title="Platform control room" nav={nav} active={tab} actions={<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={refresh}>Refresh</Button><a className="button secondary inline-flex items-center" href="/support">Support</a><a className="button secondary inline-flex items-center" href="/configuration">Configuration</a><Button variant="ghost" onClick={()=>{clearSession();setLogged(false)}}>Sign out</Button></div>}>
   <div className="mb-5 flex gap-2 overflow-auto pb-1">{nav.map(n=><Button key={n} variant={tab===n?"primary":"ghost"} onClick={()=>setTab(n)}>{n}</Button>)}</div>

   {tab==="Dashboard"&&<>
     <div className="grid cols-4 mb-5"><Stat label="24h GMV" value={money(kpi?.gmvPaise??0)}/><Stat label="Orders" value={kpi?.totalOrders??0}/><Stat label="Active restaurants" value={kpi?.activeRestaurants??0}/><Stat label="Online riders" value={kpi?.activeRiders??0}/></div>
     <section className="card"><div className="split"><div><span className="eyebrow">ONBOARDING</span><h2 className="text-xl font-bold">Restaurant approvals</h2></div><Pill tone="warning">{pendingRestaurants.length} pending</Pill></div>{pendingRestaurants.length?<div className="list mt-4">{pendingRestaurants.map(r=><div className="row" key={r.id}><div><b>{r.name}</b><div className="muted text-sm">{r.address}</div></div><div className="flex gap-2"><Button variant="danger" onClick={()=>setRestaurantStatus(r.id,"REJECTED")}>Reject</Button><Button onClick={()=>setRestaurantStatus(r.id,"APPROVED")}>Approve</Button></div></div>)}</div>:<EmptyState title="No pending applications" body="Submitted restaurant applications will appear here."/>}</section>
     <section className="card mt-5"><div className="split"><div><span className="eyebrow">DELIVERY ONBOARDING</span><h2 className="text-xl font-bold">Rider approvals</h2></div><Pill tone="warning">{pendingRiders.length} pending</Pill></div>{pendingRiders.length?<div className="list mt-4">{pendingRiders.map(r=><div className="row" key={r.id}><div><b>{r.user?.profile?.name??r.user?.email??"Applicant"}</b><div className="muted text-sm">{r.vehicleType??"Vehicle"} · {r.vehicleNumber??"Number pending"}</div></div><div className="flex gap-2"><Button variant="danger" onClick={()=>setRiderStatus(r.id,"REJECTED")}>Reject</Button><Button onClick={()=>setRiderStatus(r.id,"APPROVED")}>Approve</Button></div></div>)}</div>:<EmptyState title="No pending riders" body="Delivery partner applications will appear here."/>}</section>
   </>}

   {tab==="Orders"&&<section className="card"><div className="split"><div><span className="eyebrow">OPERATIONS</span><h2 className="text-xl font-bold">Recent orders</h2></div><Pill>{Array.isArray(data)?data.length:0}</Pill></div>{Array.isArray(data)&&data.length?<div className="list mt-4">{data.map((o:any)=><div className="row" key={o.id}><div><b>{o.orderNumber} · {o.restaurant?.name}</b><div className="muted text-sm">{o.user?.profile?.name??o.user?.email??"Customer"} · {o.status.replaceAll("_"," ")} · {money(o.totalPaise)}</div></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>dispatch(o.id)}>Dispatch rider</Button>{!["REFUNDED","CANCELLED"].includes(o.status)&&<Button variant="danger" onClick={()=>refundOrder(o)}>Refund</Button>}</div></div>)}</div>:<EmptyState title="No orders" body="Orders will appear here."/>}</section>}

   {tab==="Restaurants"&&<section className="card"><div className="split"><h2 className="text-xl font-bold">Restaurants</h2><Pill>{Array.isArray(data)?data.length:0}</Pill></div>{Array.isArray(data)&&data.length?<div className="list mt-4">{data.map((r:any)=><div className="row" key={r.id}><div><b>{r.name}</b><div className="muted text-sm">{r.city?.name} · {r.status.replaceAll("_"," ")} · {r._count?.menuItems??0} menu items · {r._count?.orders??0} orders</div></div><div className="flex gap-2">{r.status!=="APPROVED"&&<Button onClick={()=>setRestaurantStatus(r.id,"APPROVED")}>Approve</Button>}{r.status==="APPROVED"&&<Button variant="danger" onClick={()=>setRestaurantStatus(r.id,"SUSPENDED")}>Suspend</Button>}</div></div>)}</div>:<EmptyState title="No restaurants" body="Restaurant records will appear here."/>}</section>}

   {tab==="Delivery Partners"&&<section className="card"><h2 className="text-xl font-bold">Delivery partners</h2>{Array.isArray(data)&&data.length?<div className="list mt-4">{data.map((r:any)=><div className="row" key={r.id}><div><b>{r.user?.profile?.name??r.user?.email??"Rider"}</b><div className="muted text-sm">{r.status} · {r.online?"Online":"Offline"} · {r.vehicleType??"Vehicle"} {r.vehicleNumber??""} · {r._count?.assignments??0} assignments</div></div><div className="flex gap-2">{r.status!=="APPROVED"&&<Button onClick={()=>setRiderStatus(r.id,"APPROVED")}>Approve</Button>}{r.status==="APPROVED"&&<Button variant="danger" onClick={()=>setRiderStatus(r.id,"REJECTED")}>Disable</Button>}</div></div>)}</div>:<EmptyState title="No riders" body="Delivery partners will appear here."/>}</section>}

   {tab==="Customers"&&<section className="card"><h2 className="text-xl font-bold">Customers</h2>{Array.isArray(data)&&data.length?<div className="list mt-4">{data.map((u:any)=><div className="row" key={u.id}><div><b>{u.profile?.name??u.email??u.phone??"Customer"}</b><div className="muted text-sm">{u.email??u.phone} · {u.status} · {u._count?.orders??0} orders</div></div><div className="flex gap-2">{u.status!=="ACTIVE"&&<Button onClick={()=>setCustomerStatus(u.id,"ACTIVE")}>Activate</Button>}{u.status==="ACTIVE"&&<Button variant="danger" onClick={()=>setCustomerStatus(u.id,"SUSPENDED")}>Suspend</Button>}</div></div>)}</div>:<EmptyState title="No customers" body="Customer accounts will appear here."/>}</section>}

   {tab==="Payments"&&<section className="card"><h2 className="text-xl font-bold">Payments</h2>{Array.isArray(data)&&data.length?<div className="list mt-4">{data.map((p:any)=><div className="row" key={p.id}><div><b>{p.order?.orderNumber} · {p.provider}</b><div className="muted text-sm">{p.method??"Method"} · {p.status.replaceAll("_"," ")} · {p.order?.restaurant?.name}</div></div><b>{money(p.amountPaise)}</b></div>)}</div>:<EmptyState title="No payments" body="Payment attempts will appear here."/>}</section>}

   {tab==="Refunds"&&<section className="card"><h2 className="text-xl font-bold">Refunds</h2>{Array.isArray(data)&&data.length?<div className="list mt-4">{data.map((r:any)=><div className="row" key={r.id}><div><b>{r.order?.orderNumber} · {r.order?.restaurant?.name}</b><div className="muted text-sm">{r.status.replaceAll("_"," ")} · {r.reason}</div></div><b>{money(r.amountPaise)}</b></div>)}</div>:<EmptyState title="No refunds" body="Refunds will appear here."/>}</section>}

   {tab==="Promotions"&&<section className="card"><div className="split"><div><h2 className="text-xl font-bold">Promotions</h2><p className="muted text-sm">Homepage and sponsored campaigns.</p></div><Button onClick={createPromotion}>Create promotion</Button></div>{Array.isArray(data)&&data.length?<div className="list mt-4">{data.map((p:any)=><div className="row" key={p.id}><div><b>{p.title}</b><div className="muted text-sm">{p.kind} · {p.active?"Active":"Inactive"} {p.sponsored?"· Sponsored":""}</div></div><span>{p.restaurant?.name??"Platform-wide"}</span></div>)}</div>:<EmptyState title="No promotions" body="Create the first promotional campaign."/>}<Button variant="secondary" onClick={sendCampaign} style={{marginTop:16}}>Send in-app campaign</Button></section>}

   {tab==="Reviews"&&<section className="card"><h2 className="text-xl font-bold">Review moderation</h2>{Array.isArray(data)&&data.length?<div className="list mt-4">{data.map((r:any)=><div key={r.id} className="rounded-xl border border-[#e9e4dc] p-3"><div className="split"><b>{r.restaurant?.name} · ★ {r.restaurantRating}</b><Pill>{r.status}</Pill></div><p className="mt-2 text-sm">{r.text??"No text"}</p><div className="mt-3 flex gap-2"><Button onClick={()=>moderateReview(r.id,"PUBLISHED")}>Publish</Button><Button variant="danger" onClick={()=>moderateReview(r.id,"HIDDEN")}>Hide</Button></div></div>)}</div>:<EmptyState title="No reviews" body="Reviews will appear here."/>}</section>}

   {tab==="Finance"&&<section className="stack"><div className="grid cols-4"><Stat label="Captured payments" value={money(data?.capturedPaymentsPaise??0)}/><Stat label="Payment count" value={data?.capturedPaymentCount??0}/><Stat label="Refunded" value={money(data?.refundsPaise??0)}/><Stat label="Refund count" value={data?.refundCount??0}/></div><div className="grid cols-2"><section className="card"><h2 className="font-bold">Restaurant settlements</h2><div className="list mt-3">{data?.restaurantSettlements?.slice(0,20).map((s:any)=><div className="row" key={s.id}><span>{s.restaurant?.name}</span><b>{money(s.payoutPaise)}</b></div>)}</div></section><section className="card"><h2 className="font-bold">Rider earnings</h2><div className="list mt-3">{data?.riderEarnings?.slice(0,20).map((e:any)=><div className="row" key={e.id}><span>{e.partner?.user?.profile?.name??"Rider"}</span><b>{money(e.totalPaise)}</b></div>)}</div></section></div></section>}

   {tab==="Analytics"&&<section className="card"><h2 className="text-xl font-bold">7-day product events</h2>{data?.events?.length?<div className="grid cols-4 mt-4">{data.events.map((e:any)=><Stat key={e.name} label={e.name.replaceAll("_"," ")} value={e.count}/>)}</div>:<EmptyState title="No analytics events" body="Tracked customer actions will aggregate here."/>}</section>}

   {tab==="Audit Logs"&&<section className="card"><h2 className="text-xl font-bold">Audit trail</h2>{Array.isArray(data)&&data.length?<div className="list mt-4">{data.map((a:any)=><div className="row" key={a.id}><div><b>{a.action}</b><div className="muted text-sm">{a.resourceType} {a.resourceId??""}</div></div><span className="muted text-xs">{new Date(a.createdAt).toLocaleString()}</span></div>)}</div>:<EmptyState title="No audit events" body="Privileged actions will appear here."/>}</section>}

   {tab==="System"&&<><section className="grid cols-2"><div className="card"><h2 className="text-xl font-bold">Cities & service zones</h2>{Array.isArray(data)&&data.length?<div className="list mt-4">{data.map((c:any)=><div key={c.id} className="rounded-xl border border-[#e9e4dc] p-3"><b>{c.name}, {c.state}</b><div className="muted text-sm">{c._count?.restaurants??0} restaurants</div><div className="mt-2 flex flex-wrap gap-1">{c.zones?.map((z:any)=><Pill key={z.id}>{z.name} · {Number(z.radiusKm)} km</Pill>)}</div></div>)}</div>:<EmptyState title="No cities" body="Configure a launch city and service zones."/>}</div><div className="card"><h2 className="text-xl font-bold">Platform tools</h2><div className="mt-4 flex flex-col items-start gap-3"><a href="/configuration" className="button secondary inline-flex items-center">Feature flags</a><a href="/support" className="button secondary inline-flex items-center">Support dashboard</a><Button variant="secondary" onClick={sendCampaign}>Notification campaign</Button></div></div></section><section className="card mt-5"><div className="split"><div><span className="eyebrow">PROVIDER READINESS</span><h2 className="text-xl font-bold">External integrations</h2></div><Pill tone={integrations&&Object.values(integrations).every((x:any)=>x.configured)?"success":"warning"}>{integrations?Object.values(integrations).filter((x:any)=>x.configured).length+"/"+Object.keys(integrations).length+" ready":"Super-admin only"}</Pill></div>{integrations?<div className="grid cols-4 mt-4">{Object.entries(integrations).map(([name,value]:any)=><div key={name} className="rounded-xl border border-[#e9e4dc] p-3"><div className="split"><b className="capitalize">{name}</b><Pill tone={value.configured?"success":"warning"}>{value.configured?"Ready":"Pending"}</Pill></div><div className="muted mt-2 text-xs">{value.provider}</div>{!value.configured&&value.missing?.length>0&&<div className="muted mt-2 text-xs">Replace: {value.missing.join(", ")}</div>}</div>)}</div>:<p className="muted mt-3 text-sm">Provider readiness is visible to super administrators without exposing secret values.</p>}</section></>}
   {message&&<div className="toast">{message}</div>}
 </PortalShell>;
}
