"use client";
import {useEffect,useState} from "react";
import {api,Brand,Button,Pill} from "@ppm/ui";

export default function PartnerJoin(){
 const [logged,setLogged]=useState(false),[kind,setKind]=useState<"restaurant"|"delivery">("restaurant"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[result,setResult]=useState<any>(null);
 const [restaurant,setRestaurant]=useState({name:"",phone:"",email:"",address:"",latitude:18.783,longitude:83.426});
 const [rider,setRider]=useState({vehicleType:"BIKE",vehicleNumber:""});
 useEffect(()=>setLogged(!!sessionStorage.getItem("ppm_access_token")),[]);
 function useLocation(){if(!navigator.geolocation){setMessage("Location is not available in this browser");return}navigator.geolocation.getCurrentPosition(p=>setRestaurant(v=>({...v,latitude:Number(p.coords.latitude.toFixed(6)),longitude:Number(p.coords.longitude.toFixed(6))})),()=>setMessage("Could not access your location"),{enableHighAccuracy:true,timeout:10000})}
 async function submitRestaurant(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r:any=await api("/onboarding/restaurant",{method:"POST",body:JSON.stringify({...restaurant,email:restaurant.email||undefined})});setResult(r);setMessage("Restaurant application submitted") }catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function submitRider(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r:any=await api("/onboarding/delivery",{method:"POST",body:JSON.stringify(rider)});setResult(r);setMessage("Delivery partner application submitted") }catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 if(!logged)return <main className="mx-auto max-w-xl p-5 pt-16"><a href="/"><Brand/></a><div className="card mt-8 text-center"><span className="eyebrow">PARTNER ONBOARDING</span><h1 className="mt-3 text-3xl font-black">Sign in before applying</h1><p className="muted mt-2">Create a normal PPM Bites account first. The same account becomes your partner account after application.</p><a href="/account" className="button primary mt-5 inline-flex items-center">Sign in or create account</a></div></main>;
 if(result)return <main className="mx-auto max-w-xl p-5 pt-16"><a href="/"><Brand/></a><div className="card mt-8 text-center"><div className="text-5xl">✓</div><h1 className="mt-3 text-3xl font-black">Application received</h1><p className="muted mt-2">Status: <b>{result.status}</b></p><p className="muted">Your partner role is active for portal access; operations remain pending until review is completed.</p><a href="/" className="button secondary mt-5 inline-flex items-center">Back to PPM Bites</a></div></main>;
 return <main className="mx-auto max-w-3xl p-4 md:p-8"><div className="split mb-8"><a href="/"><Brand/></a><a href="/" className="button ghost inline-flex items-center">← Home</a></div><section className="card"><span className="eyebrow">JOIN PPM BITES</span><h1 className="mt-2 text-3xl font-black">Partner onboarding</h1><p className="muted mt-2">Applications are reviewed before a restaurant or rider can serve customers.</p><div className="mt-5 flex gap-2"><Button variant={kind==="restaurant"?"primary":"secondary"} onClick={()=>setKind("restaurant")}>Restaurant</Button><Button variant={kind==="delivery"?"primary":"secondary"} onClick={()=>setKind("delivery")}>Delivery partner</Button></div>
 {kind==="restaurant"?<form className="stack mt-6" onSubmit={submitRestaurant}><input className="input" required minLength={2} placeholder="Restaurant name" value={restaurant.name} onChange={e=>setRestaurant({...restaurant,name:e.target.value})}/><div className="grid cols-2"><input className="input" required placeholder="Phone" value={restaurant.phone} onChange={e=>setRestaurant({...restaurant,phone:e.target.value})}/><input className="input" type="email" placeholder="Business email (optional)" value={restaurant.email} onChange={e=>setRestaurant({...restaurant,email:e.target.value})}/></div><textarea className="input min-h-24 py-3" required placeholder="Full restaurant address" value={restaurant.address} onChange={e=>setRestaurant({...restaurant,address:e.target.value})}/><div className="grid cols-2"><input className="input" type="number" step="any" aria-label="Latitude" value={restaurant.latitude} onChange={e=>setRestaurant({...restaurant,latitude:Number(e.target.value)})}/><input className="input" type="number" step="any" aria-label="Longitude" value={restaurant.longitude} onChange={e=>setRestaurant({...restaurant,longitude:Number(e.target.value)})}/></div><Button type="button" variant="secondary" onClick={useLocation}>Use current location</Button><div className="rounded-xl bg-[#f8f5ef] p-3 text-sm"><Pill tone="warning">Review required</Pill> Restaurant stays offline until approval and menu setup are complete.</div><Button disabled={busy} type="submit">{busy?"Submitting…":"Submit restaurant application"}</Button></form>
 :<form className="stack mt-6" onSubmit={submitRider}><select className="input" value={rider.vehicleType} onChange={e=>setRider({...rider,vehicleType:e.target.value})}><option value="BIKE">Bike</option><option value="SCOOTER">Scooter</option><option value="CYCLE">Cycle</option></select><input className="input" required minLength={4} placeholder="Vehicle number" value={rider.vehicleNumber} onChange={e=>setRider({...rider,vehicleNumber:e.target.value})}/><div className="rounded-xl bg-[#f8f5ef] p-3 text-sm"><Pill tone="warning">Documents pending</Pill> Delivery access stays pending until admin verification.</div><Button disabled={busy} type="submit">{busy?"Submitting…":"Submit delivery application"}</Button></form>}
 </section>{message&&<div className="toast">{message}</div>}</main>
}