FROM node:22-alpine AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run db:generate
RUN npm run build -w @ppm/core
RUN npm run build -w @ppm/database
RUN npm run build -w @ppm/api

FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app /app
EXPOSE 4000
CMD ["npm","run","start","-w","@ppm/api"]
