FROM node:22-alpine AS build
ARG WORKSPACE
ENV WORKSPACE=$WORKSPACE
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build -w @ppm/core
RUN npm run build -w "$WORKSPACE"
ENV NODE_ENV=production
ENV PORT=3000
CMD ["sh","-c","npm run start -w $WORKSPACE -- -p $PORT"]
